imports:
- { resource: 'services.yml' }

parameters:
  module_settings:
    configuration:
    hooks:
    - 'actionDispatcherBefore'
    tabs:
    - {name: 'Manticore', parent_class_name: 'AdminParentModulesSf', class_name: 'AdminManticoreTab', visible: false}
    - {name: 'Info', parent_class_name: 'AdminManticoreTab', class_name: 'AdminManticoreInfo'}