services:
    manticore.module:
        class: 'Manticore'
        factory: ['Module', 'getInstanceByName']
        arguments:
            - 'manticore'

#    Installers
    install.tab:
        class: 'Evolutive\Manticore\Install\Tab'
        arguments:
            - '%module_settings%'

    installer:
        class: 'Evolutive\Manticore\Install\Installer'
        arguments:
            - '@manticore.module'
            - '%module_settings%'

    uninstaller:
        class: 'Evolutive\Manticore\Install\Uninstaller'
        arguments:
            - '@manticore.module'
            - '%module_settings%'