services:

    prestashop.module.manticore.uploader.supplier_extra_image_uploader:
        class: PrestaShop\Module\Manticore\Uploader\SupplierExtraImageUploader
        arguments:
          - '@prestashop.module.manticoreextendsymfonyform.repository.supplier_extra_image_repository'

    prestashop.module.manticoreextendsymfonyform.repository.supplier_extra_image_repository:
        class: PrestaShop\Module\Manticore\Repository\SupplierExtraImageRepository
        public: true
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
          - PrestaShop\Module\ManitocoreExtendSymfonyForm\Entity\SupplierExtraImage

    # Decorators
    # ref. https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/override-decorate-controller/#decorate-the-controller
    prestashop.module.manticore.products.controller:
        class: 'PrestaShop\Module\Manticore\Controller\AdminProductController'
        decorates: 'PrestaShopBundle\Controller\Admin\ProductController'
        arguments: 
            - '@prestashop.module.manticore.products.controller.inner'

    prestashop.module.manticore.customers.controller:
        class: 'PrestaShop\Module\Manticore\Controller\AdminCustomerController'
        decorates: 'PrestaShopBundle\Controller\Admin\Sell\Customer\CustomerController'
        arguments:
            - '@prestashop.module.manticore.customers.controller.inner'

    prestashop.module.manticore.address.controller:
        class: 'PrestaShop\Module\Manticore\Controller\AdminAddressController'
        decorates: 'PrestaShopBundle\Controller\Admin\Sell\Address\AddressController'
        arguments:
            - '@prestashop.module.manticore.address.controller.inner'

    prestashop.module.manticore.orders.controller:
        class: 'PrestaShop\Module\Manticore\Controller\AdminOrderController'
        decorates: 'PrestaShopBundle\Controller\Admin\Sell\Order\OrderController'
        arguments:
            - '@prestashop.module.manticore.orders.controller.inner'

    prestashop.module.manticore.cms.controller:
        class: 'PrestaShop\Module\Manticore\Controller\AdminCmsController'
        decorates: 'PrestaShopBundle\Controller\Admin\Improve\Design\CmsPageController'
        arguments: 
            - '@prestashop.module.manticore.cms.controller.inner'