services:
    manticore.module:
        class: 'Manticore'
        factory: ['Module', 'getInstanceByName']
        arguments:
            - 'manticore'

    # Installers
    install.tab:
        class: 'Evolutive\Manticore\Install\Tab'
        arguments:
            - '%module_settings%'

    installer:
        class: 'Evolutive\Manticore\Install\Installer'
        arguments:
            - '@manticore.module'
            - '%module_settings%'

    uninstaller:
        class: 'Evolutive\Manticore\Install\Uninstaller'
        arguments:
            - '@manticore.module'
            - '%module_settings%'

    # Decorators
    # ref. https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/override-decorate-controller/#decorate-the-controller
    manticore_products_controller:
        class: 'Evolutive\Manticore\Controller\AdminProductController'
        decorates: PrestaShopBundle\Controller\Admin\Improve\Sell\Catalog\Product\ProductController
        arguments: 
            - '@manticore_products_controller.inner'

    manticore_orders_controller:
        class: 'Evolutive\Manticore\Controller\AdminOrderController'
        decorates: PrestaShopBundle\Controller\Admin\Improve\Sell\Order\OrderController
        arguments:
            - '@manticore_orders_controller.inner'

    manticore_customers_controller:
        class: 'Evolutive\Manticore\Controller\AdminCustomerController'
        decorates: PrestaShopBundle\Controller\Admin\Improve\Sell\Customer\CustomerController
        arguments:
            - '@manticore_customers_controller.inner'

    manticore_address_controller:
        class: 'Evolutive\Manticore\Controller\AdminAddressController'
        decorates: PrestaShopBundle\Controller\Admin\Improve\Sell\Address\AddressController
        arguments:
            - '@manticore_address_controller.inner'